name: Check pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

  push:
    tags:
      - v[0-9]+

jobs:
  get-release-info:
    name: Get release info
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get author info
        run: git show ${{github.ref_name}} | grep Author
      - name: Get date info
        run: git show ${{github.ref_name}} | grep Date
      - name: Find issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: "find-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-state: "open"
          title-includes: ${{github.ref_name}}
          labels: "RELEASE"

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: ESLint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build project
        run: npm run build

  test-unit:
    name: Unit test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run unit test
        run: npm run test-ci:unit
        env:
          JEST_JUNIT_OUTPUT_NAME: jest.xml

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report jest test
          path: jest.xml
          reporter: jest-junit

  test-e2e:
    name: e2e test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Install playwright
        run: npx playwright install --with-deps chromium

      - name: Run e2e test
        run: npm run test-ci:e2e
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: playwright.xml

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report playwright test
          path: playwright.xml
          reporter: jest-junit
