name: Check pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
